### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by Zekfad** [Zekfad/fetch_client#13]
There are still some errors pop up, due to language version restrictions.
To allow generics in JS interop - language must be set to 3.3.

Current version of client `1.0.2` will be the last to support Dart >=2.19 <4, in the next version I'll set minimum language version to 3.3.
Public API won't change, but it will be feature update, Dart >=3.3 users will benefit from updated interop, while old versions will continue to use `>=1.0.2 <1.1.0`, default caret constraint on `fetch_api` will leave place for critical fixes to the old branch.

Checklist:
- [x] Fetch API migrate to `dart:js_interop`
- [x] Bump major and language version for `fetch_api`
- [x] Remove compatibility layer
- [x] Bump feature and language for `fetch_client`
- [x] Migrate internals to new `fetch_api`

**Comment by Zekfad** [comment]
CHROME 118 DOESNT HAVE `ITERATOR`
![fuck](https://github.com/Zekfad/fetch_client/assets/8970959/711f4a44-f1e4-4495-9102-5572684fb2ef)

**Comment by Zekfad** [comment]
Decided to move straight to 3.3, it has `inline-class` (extension types) enabled by default without experimental flag.
Currently it is beta.
Also this change will introduce dependency on `package:web` instead of `dart:html`, but on the other side we'll have full wasm ready bindings.

**Comment by Zekfad** [comment]
Everything is almost ready for publishing, would be helpful to have someone else test the package in field.

Tests are good except for new Content-Length test: https://github.com/dart-lang/http/issues/1121

**Comment by davidmigloz** [comment]
I ran all [`openai_dart`](https://pub.dev/packages/openai_dart) tests in chrome using the latest commit in main and all were green 🙂

Thanks for your work!

**Comment by Zekfad** [comment]
Published pre-release https://pub.dev/packages/fetch_client/versions/1.1.0-wasm
As soon as Dart 3.3 will be stable, I'll publish as a main release.
