### ISSUE TITLE
is there anything I can contribute with in fetch_client package

### ISSUE THREAD

**Issue by anasfik** [Zekfad/fetch_client#16]
Hi, thank you for your work, the package is very helpful, I wonder if there is something I can help with here.

Anas.

**Comment by Zekfad** [comment]
Hi! Thank you for your interest in contribution.
Currently fetch_client is missing only 1 feature: #15, I'm planning to release it soon.
But most of the job is needed in `fecth_api` (#13), we need to migrate to new JS interop.
Some examples of new interop can be found in package:web, e.g. https://github.com/dart-lang/web/blob/main/lib/src/dom/shared_storage.dart

It would be a huge help to migrate `fetch_api`, to future JS interop (this will make it `fetch_client` WASM-ready).
