### ISSUE TITLE
Get request failure

### ISSUE THREAD

**Issue by basil59** [Zekfad/fetch_client#17]
This is my first project using http client so it could be a dumb mistake on my part.

Been working on a flutter app that downloads a file from a remote server using Get; the app uses the standard http client for Windows and Fetch client for web.

The Windows app downloads the file with no issues but the Fetch version running on Chrome fails.

Here's a minimal test app that shows the issue (modified version of [fetch_client_example.dart](https://github.com/Zekfad/fetch_client/blob/master/example/fetch_client_example.dart)
The first Get request succeeds, but the second fails.

```
import 'package:fetch_client/fetch_client.dart';
import 'package:http/http.dart';

void test(String auth, String path) async {
  try {
    final client = FetchClient(mode: RequestMode.cors);
    final uri = Uri.https(auth, path);
    final response = await client.send(Request('GET', uri));

    print(' $path statusCode: ${response.statusCode}');
  } catch (e) {
    print('$path exception: $e');
  }
}

void main() {
  test('jsonplaceholder.typicode.com', '/todos/1');
  test('link.testfile.org', '/PDF10MB');
}
```
here's the test app output:
```
/todos/1 statusCode: 200
/PDF10MB exception: ClientException: Failed to execute fetch: TypeError: Failed to fetch, uri=https://link.testfile.org/PDF10MB

```
version info:
fetch_client: ^1.0.2
http: ^1.2.1
Windows 11 23H2
Chrome Version 123.0.6312.59 (Official Build) (64-bit)
Flutter 3.19.4 • channel stable 
Framework • revision 68bfaea224 (2 days ago) • 2024-03-20 15:36:31 -0700
Engine • revision a5c24f538d
Tools • Dart 3.3.2 • DevTools 2.31.1

**Comment by Zekfad** [comment]
I'll look at your example little later, but I have some tips to suggest:
Check that site you're trying to access sends CORS headers. This may be an issue because browsers have a security mechanic to prevent malicious access to data on another domain (e.g. disallow random site from using Google API to read your emails).
On IO platforms (Android, Windows, iOS, Mac) this is not an issue because executable app have direct access to TCP/IP stack and not a subject to such restrictions.

**Comment by Zekfad** [comment]
Just checked, yes your host does not supply CORS for requests. You have 2 options:
* Use a different host for your testing
* Use CORS proxy while testing the app

**Comment by basil59** [comment]
Thank you so much for your prompt and useful response!
