### ISSUE TITLE
NotSupportedError: ReadableStream uploading is not supported

### ISSUE THREAD

**Issue by lcm1475** [Zekfad/fetch_client#4]
NotSupportedError: ReadableStream uploading is not supported
This error occurs in Safari on iOS and macOS, but everything works fine on other platforms.

**Comment by Zekfad** [comment]
According to MDN this feature is unavailable on Safari browser, sadly there are no fix for that, all I can do is to add note to documentation:

https://developer.mozilla.org/en-US/docs/Web/API/Request#:~:text=Send%20ReadableStream%20in%20request%20body
