### ISSUE TITLE
FetchClient(mode: RequestMode.cors) error

### ISSUE THREAD

**Issue by agreensh** [Zekfad/fetch_client#9]
With the latest Flutter stable version, now get this error when using "FetchClient(mode: RequestMode.cors)":
 
 "Expected a value of type 'Iterator', but got one of type 'DomIterator'"
 
 Setup:

   • Flutter version 3.13.4 on channel stable at /Users/andy/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (28 hours ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

**Comment by ganigeorgiev** [comment]
Here is also minimal reproducible example:

0. `pubspec.yaml`
    ```yaml
    name: example
    version: 0.0.1

    environment:
      sdk: '>=3.0.0 <4.0.0'

    dependencies:
      fetch_client: ^1.0.0

    dev_dependencies:
      build_runner: '^2.0.0'
      build_web_compilers: '^4.0.0'
    ```

1. `example/example.dart`
    ```dart
    import 'dart:html';
    import 'package:http/http.dart' as http;
    import 'package:fetch_client/fetch_client.dart';

    void main() {
      // random request bin url
      // (could be inspected at https://public.requestbin.com/r/en80s0kpkubki)
      final url = Uri.parse('https://en80s0kpkubki.x.pipedream.net');

      final sendBtn = document.getElementById('sendBtn');

      sendBtn?.onClick.listen((event) {
        final req = http.MultipartRequest('POST', url);

        req.fields["demo"] = "123";

        FetchClient(mode: RequestMode.cors).send(req).then((result) {
          print('SUCCESS!');
        });
      });
    }
    ```

2. `example/index.html`
    ```html
    <!DOCTYPE html>
    <html>
      <head>
        <script defer src="example.dart.js"></script>
      </head>
      <body>
        <button id="sendBtn">Send</button>
      </body>
    </html>
    ```

3. Run `dart pub global run webdev serve example`


**Strangely note that the error seems to be reproducible only in Chrome 117, but it works fine in Chrome 115 or Firefox 115 (_I haven't updated Firefox to check if it is reproducible in newer version there too_).**

Here is the raw JS error:

```js
errors.dart:285 Uncaught (in promise) Error: Expected a value of type 'Iterator', but got one of type 'DomIterator'
    at Object.throw_ [as throw] (errors.dart:285:21)
    at Object.castError (errors.dart:121:3)
    at dart.NonStaticInteropType.new.as (types.dart:245:34)
    at Object.HeadersInstanceMembers$124_entries [as HeadersInstanceMembers|_entries] (headers.dart:72:38)
    at Object.HeadersInstanceMembers$124entries [as HeadersInstanceMembers|entries] (headers.dart:101:5)
    at fetch_client.dart:157:47
    at fetch_client.FetchClient.new.send (fetch_client.dart:158:31)
    at send.next (<anonymous>)
    at async_patch.dart:45:50
    at _RootZone.runUnary (zone.dart:1661:54)
    at _FutureListener.thenAwait.handleValue (future_impl.dart:147:18)
    at handleValueCallback (future_impl.dart:784:44)
    at _Future._propagateToListeners (future_impl.dart:813:13)
    at [_completeWithValue] (future_impl.dart:584:5)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:657:7)
    at Object._microtaskLoop (schedule_microtask.dart:40:11)
    at _startMicrotaskLoop (schedule_microtask.dart:49:5)
    at async_patch.dart:177:15
```

**Comment by Zekfad** [comment]
I think it may be related to the fact that there are new interop with `@Native` in new SDK.
I was planning to migrate this library to new interop to make it ready for future wasm release.
I'll try to investigate this issue, it it only a problem on specific browser version or general issue? You may want to report it to dart-sdk.

**Comment by agreensh** [comment]
Seems to be a problem only on latest Chrome (Chrome 117.0.5938.62 is what I'm testing against).
Still working in Safari and FireFox, and haven't tested on Edge / Explorer.

**Comment by Zekfad** [comment]
Seems like a target browser bug, try to report to `dart-lang/sdk`.
I have beta Chrome on my Windows laptop, and can confirm that it's the issue in Chrome 117, as Edge 116 works fine.

**Comment by Zekfad** [comment]
More generally the issue is that in Chrome < 117, JS interop can confirm that `Iterator` instance of [`Headers.entries()`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/entries) conforms to my custom Iterator description (see: https://github.com/Zekfad/fetch_api/blob/master/lib/src/iterator.dart )
This iterator is implemented via internal constructor which seems to be exposed in 117. My guess is that compiler confuses `Iterator` with `NodeIterator` and hence the issue:
![image](https://github.com/Zekfad/fetch_client/assets/8970959/f3da94e5-079a-45ee-a8eb-a8afcde15a29)

**Comment by bsubash2054** [comment]
I am facing similar issues on Chrome. Works fine on Safari.

**Comment by flutterdev06** [comment]
Any updates on this issue?

**Comment by Zekfad** [comment]
Issue must be resolved now, as I found workaround for this particular case.
